---
title: JHS Ar-condicionado
timezone: UTC
collections:
  clientes:
    title: Clientes
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:categories/:year/:month/:day/:title.html"
telefones: "(15) 3213-9347 / 9 9600-0125"
endereco: Rua Pedro Sola Verdun, 896
bairro: Jardim J. S. Carvalho
cidade: Sorocaba – SP
description: 'Mais de 10 anos de experiência no ramo de venda, instalação e manutenção
  em aparelhos de ar condicionado. Atendimento rápido e eficiente para empresas, estabelecimentos
  comerciais e residências, valorizando o relacionamento com os clientes com responsabilidade
  e transparência.

'
baseurl: 
url: http://jhsar.com.br
cover: https://c2.staticflickr.com/8/7512/27284014190_3ef3fc1e7e_b.jpg
markdown: kramdown
livereload: true
exclude:
- desktop.ini
- gulpfile.js
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- package-lock.json
sass:
  style: compressed
