# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JHS Ar-condicionado
telefones: (15) 3213-9347 / 9 9604-1334
endereco: 'Rua Pedro Sola Verdun, 896'
bairro: Jardim J. S. Carvalho
cidade: Sorocaba – SP﻿
description: > # this means to ignore newlines until "baseurl:"
  Mais de 10 anos de experiência no ramo de venda, instalação e manutenção em aparelhos
  de ar condicionado. Atendimento rápido e eficiente para empresas, estabelecimentos
  comerciais e residências, valorizando o relacionamento com os clientes com
  responsabilidade e transparência.
baseurl: "/JHS" # the subpath of your site, e.g. /blog
url: "http://jhsar.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
